version: '3.8'

services:
  wordpress:
    image: bridge-builder-plugin-wordpress
    network_mode: host  # This gives direct access to host network
    environment:
      WORDPRESS_DB_HOST: localhost
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: unless-stopped
    # Note: With host networking, we don't need port mapping
    # The container will use the host's network directly

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    # MySQL will be accessible on localhost:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    network_mode: host  # Also use host networking for consistency
    environment:
      PMA_HOST: localhost
      PMA_PORT: 3306
    restart: unless-stopped
    # PhpMyAdmin will be accessible on localhost:8081

volumes:
  db_data: 